# Generated by Django 3.1.8 on 2021-12-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='bmi',
            field=models.CharField(default=25, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=20, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='smoke',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
