# Generated by Django 3.1.8 on 2021-12-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20211231_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11)),
                ('age', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=50)),
                ('bmi', models.CharField(max_length=4)),
                ('smoke', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='smoke',
        ),
    ]
