# Generated by Django 3.1.8 on 2021-12-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20211231_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='authtoken_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1000)),
            ],
        ),
    ]
