# Generated by Django 3.1.8 on 2022-01-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_authtoken_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='authtoken_token',
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
